[package]
name = "scene-graph"
version = "0.1.0"
edition = "2021"


[dependencies]
thunderdome = { git = "https://github.com/sanbox-irl/thunderdome" }
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"
petgraph = "0.6.2"

[[bench]]
name = "benches"
harness = false
