[package]
name = "scene-graph"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "1.0"
thunderdome = "0.6.0"

[dev-dependencies]
criterion = "0.3"
petgraph = "0.6.2"

[[bench]]
name = "benches"
harness = false
